name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Setup cache
      uses: actions/cache@v2
      with:
        path: |
          /nix/store
          ~/.cache/bazel
        key: ${{ runner.os }}-cache
    - uses: cachix/install-nix-action@v13
    - name: Build the code
      run: bazel build //...
