name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
    - uses: cachix/cachix-action@v10
      with:
        name: aveltras
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Setup bazel cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/bazel
        key: ${{ runner.os }}-bazel
    - name: Build the code
      run: bazel build //...
